apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpconfig
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tpconfig.nais.preprod.local
    - https://tpconfig.dev-fss.nais.io
    - https://tpconfig.dev.adeo.no
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  prometheus:
    enabled: true
