apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpconfig
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tpconfig.nais.adeo.no
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  prometheus:
    enabled: true
